version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    container_name: django_app

  celery:
    build:
      context: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/app
    container_name: celery
    depends_on:
      - web
